### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ewolfe** [dance2die/calendar-dates#16]
This is a great project, but it looks like the documentation link (https://sungkim.co/calendar-dates/) takes you to a page that doesn't exist.

**Comment by dance2die** [comment]
Thanks @ewolfe.

It seems like I have broken it while messing around with my domain.
I will update it to the GitHub URL, which is https://dance2die.github.io/calendar-dates/

**Comment by ewolfe** [comment]
Thank you so much!

Ps I'm really loving this. I have a small React component that's going to make use of this. I'll share it with you when I release it :)

**Comment by dance2die** [comment]
No. Thank YOU 😛
I was able to correct the documentation link thanks you.

Glad that you like the package there.
And I'd love to see your ⚛️ component 👍
