### ISSUE TITLE
Unexpected array in getMatrix

### ISSUE THREAD

**Issue by ewolfe** [dance2die/calendar-dates#20]
### Unexpected behavior

All the dates in the last array of getMatrix belong to the next month.

### Expected behavior

If all the dates belong to the next month, then the array should probably just not be returned.

### Steps to reproduce

https://codesandbox.io/s/10lo3lqn3l

```js
import CalendarDates from "calendar-dates";

const calendarDates = new CalendarDates();

calendarDates.getMatrix(new Date("2018-10-07")).then(dates => {
  console.log(dates);
  document.getElementById("app").innerHTML = `
    <pre>
${JSON.stringify(dates[dates.length - 1], null, 2)}
    </pre>
  `;
});
```

**Comment by ewolfe** [comment]
@dance2die I can open a pull request to fix this. We can just check if the 7th item from the last belongs to the next month and then splice it. Does that sound like an okay approach?

**Comment by dance2die** [comment]
Hi @ewolfe Sorry to get back to ya late.

If `next` month dates should not be displayed, shouldn't `previous` month dates also should not include iso date?

**Comment by ewolfe** [comment]
No, sorry. It's not that all `next` month dates should not be displayed, it's that _too many_ get displayed. For example, there's no need to display this last row here:

![image](https://user-images.githubusercontent.com/32533397/46778544-0a69d180-ccc9-11e8-840f-a1bf8e4784e6.png)

**Comment by dance2die** [comment]
Ah, I see what you mean.

I went with the design decision to be consistent with many of calendars available.

Google, Outlook, & Windows as an example.
![image](https://user-images.githubusercontent.com/8465237/46799573-1e422180-cd23-11e8-8de8-286cf8a032f4.png)

So I'd like to leave it as it is and let users decide whether to filter it out or not.

**Comment by ewolfe** [comment]
Ah okay, that's fair! Thanks for sharing those screenshots. Will go ahead and close this issue :)
