### ISSUE TITLE
Why is this library async?

### ISSUE THREAD

**Issue by ewolfe** [dance2die/calendar-dates#23]
Is there any reason the main interfaces (`getDates` and `getMatrix`) are exposed as a promise? It looks like the backing [`getDatesWithMetadata`](https://github.com/dance2die/calendar-dates/blob/4736cde57a95ef85d76fd8f0928e14424b2d5dee/src/dateutil.js#L31) can be implemented in a synchronous manner instead of returning a promise.

**Comment by dance2die** [comment]
Closing after a discussions in  #24.
