### ISSUE TITLE
Create a CI/CD pipeline

### ISSUE THREAD

**Issue by dance2die** [dance2die/calendar-dates#28]
## To Dos

- [X] Choose CI/CD framework
  - CircleCI
- [X] Test PRs
- [x] Add a button to publish directly from PR after running tests.
- [x] Add a bundle size check/warning

**Comment by ewolfe** [comment]
I would love to help out on this. I can open a pull request to configure a travis-ci setup. Just let me know.

**Comment by dance2die** [comment]
Hi @ewolfe I started using CircleCI and would like to use it for this one as well, which I am working on now.

**Comment by dance2die** [comment]
I am not sure if it's possible to add you later as a contributor in CircleCI so you can add bundle size checks and warnings later on... 🤔

**Comment by dance2die** [comment]
This is now done... :awyeah:
